# This is forked from pmdsky-debug.

name: Check pmdsky-debug Symbols

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install resymgen
        run: cargo install resymgen
      - name: Test
        run: resymgen check --complete-version-list --explicit-versions --in-bounds-symbols --no-function-overlap --nonempty-maps --unique-symbols --data-names SCREAMING_SNAKE_CASE --function-names PascalCase symbols/*.yml
        working-directory: ./skytemple_files/_resources/pmdsky-debug/
