name: ROM Tests

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
      - release
      - version/*
    tags:
      - "*"
  pull_request: {}

jobs:
  test_with_rom:
   # This uses a self-hosted runner with access to the ROM at /rom.nds.
   runs-on: ["self-hosted", "romtest"]
   name: Runs tests with real ROM
   strategy:
     fail-fast: false
     matrix:
       python-version: [ "3.9" ]
       native: [true, false]
   steps:
   - uses: actions/checkout@v4
     with:
       submodules: 'recursive'
   - name: Set up Python ${{ matrix.python-version }}
     uses: actions/setup-python@v5
     with:
       python-version: ${{ matrix.python-version }}
   - name: Install dependencies
     run: |
       python -m pip install --upgrade pip
       pip install tox tox-gh-actions
   - name: Enable native modules
     if: matrix.native
     run: |
       echo "SKYTEMPLE_USE_NATIVE=1" >> $GITHUB_ENV
   - uses: dtolnay/rust-toolchain@stable
   - name: Test with tox
     run: tox -- -m "romtest"
     working-directory: test
     env:
       SKYTEMPLE_TEST_ROM: /rom.nds
   - run: mv test/pytest.xml test/pytest-romtest-${{ matrix.python-version }}-${{ matrix.native }}.xml
   - name: Upload Test Results
     if: always()
     uses: actions/upload-artifact@v4
     with:
       name: "Pytest ROM Test Results (Python ${{ matrix.python-version }}) - Native ${{ matrix.native }})"
       path: test/pytest-romtest-${{ matrix.python-version }}-${{ matrix.native }}.xml
